require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# TODO: in ios device, may change to >= 11 to use Stripe
platform :ios, '10.0'

target 'MyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # TODOs: may comment out use_flipper if issue
  # TODOs: or may remove -rf ios/Pods ios/Podfile.lock && npx pod-install
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end